-- base table
CREATE TABLE record_base(
	ID INT PRIMARY KEY NOT NULL,
	RED_1 INT NOT NULL,
	RED_2 INT NOT NULL,
	RED_3 INT NOT NULL,
	RED_4 INT NOT NULL,
	RED_5 INT NOT NULL,
	RED_6 INT NOT NULL,
	BLUE INT NOT NULL,
	"DATE" DATE NOT NULL
);

-- detail table
CREATE TABLE record_detail(
	ID INT PRIMARY KEY NOT NULL,
	WEEK VARCHAR(8) NOT NULL,
	SALES BIGINT,
	POOL_MONEY BIGINT,
	DETAIL_LINK VARCHAR(255),
	FOREIGN KEY(ID) REFERENCES record_base(ID)
);

-- details table
CREATE TABLE record_details(
	ID INT NOT NULL,
	TYPE INT,
	TYPE_NUM BIGINT,
	TYPE_MONEY BIGINT,
	FOREIGN KEY(ID) REFERENCES record_detail(ID)
);